name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build APK with gradle
      run: sh ./gradle build

    - name: Lint
      run: sh ./gradlew lint

    - name: List AVDs
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager list avd


