name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build APK with gradle
      run: sh ./gradle build

    - name: Lint
      run: sh ./gradlew lint

    - name: Setup a emulator
      run: |
        #sh yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0" "cmake;3.22.1" emulator "ndk;26.1.10909125" "build-tools;34.0.0" "platforms;android-34"
        sh yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-34;google_apis;x86_64"
        # Create an AVD with a name
        AVD_NAME=Pixel_C_API_34
        no | $ANDOIRD_HOME/cmdline-tools/latest/bin/avdmanager -v create avd -n ${AVD_NAME} -k "system-images;android-34;google_apis;x86_64"
        # Check if it's created
        $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager list avd


